// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmP63BbIXANHeYkj4i0SArYUK4GuvPCww',
    appId: '1:995676961816:web:7477107c5c545537b2d76d',
    messagingSenderId: '995676961816',
    projectId: 'your-destination-project',
    authDomain: 'your-destination-project.firebaseapp.com',
    storageBucket: 'your-destination-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-oQP8iTBpbSnROJHtdq-s_FyPOyXAms',
    appId: '1:995676961816:android:78af0472c41ee656b2d76d',
    messagingSenderId: '995676961816',
    projectId: 'your-destination-project',
    storageBucket: 'your-destination-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoiblcs01RyeN6S-SDrvWH2Yr9zYt69M',
    appId: '1:995676961816:ios:a67469eace6e2fc9b2d76d',
    messagingSenderId: '995676961816',
    projectId: 'your-destination-project',
    storageBucket: 'your-destination-project.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoiblcs01RyeN6S-SDrvWH2Yr9zYt69M',
    appId: '1:995676961816:ios:4d6c3d588e54da89b2d76d',
    messagingSenderId: '995676961816',
    projectId: 'your-destination-project',
    storageBucket: 'your-destination-project.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
